version: "3.4"
name: tp1

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
    networks:
      - testing_net
    ports:
      - "5672:5672"
      - "15672:15672"

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py archivo.csv
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      - server
    networks:
      - testing_net
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/archivo.csv:/archivo.csv
      - ./results:/results

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_resultados
      - OUTPUT=vuelos
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=QUEUE
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  filter_general:
    deploy:
      replicas: ${FILTER_GENERAL_REPLICAS}
    image: filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - DELIMITER=,
      - INPUT_FIELDS=legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,totalTravelDistance,segmentsDepartureTimeEpochSeconds,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
      - OUTPUT_FIELDS=legId,startingAirport,destinationAirport,totalFare,totalTravelDistance,travelDuration,segmentsArrivalAirportCode
      - INPUT=vuelos
      - OUTPUT=vuelos_filtered
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=EXCHANGE
      - REPLICAS_COUNT=${FILTER_GENERAL_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  filter_multiple:
    deploy:
      replicas: ${FILTER_MULTIPLE_REPLICAS}
    image: filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - DELIMITER=,
      - INPUT_FIELDS=legId,startingAirport,destinationAirport,totalFare,totalTravelDistance,travelDuration,segmentsArrivalAirportCode
      - OUTPUT_FIELDS=legId,startingAirport,destinationAirport,totalFare,travelDuration,segmentsArrivalAirportCode
      - INPUT=vuelos_filtered
      - OUTPUT=vuelos_multiple
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=EXCHANGE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${FILTER_MULTIPLE_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  processor_tres_escalas_o_mas:
    deploy:
      replicas: ${PROCESSOR_TRES_ESCALAS_O_MAS_REPLICAS}
    image: tres_escalas_o_mas:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_multiple
      - OUTPUT=vuelos_tres_escalas_o_mas
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=EXCHANGE
      - REPLICAS_COUNT=${PROCESSOR_TRES_ESCALAS_O_MAS_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  filter_dos_mas_rapidos:
    deploy:
      replicas: ${FILTER_DOS_MAS_RAPIDOS_REPLICAS}
    image: filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - DELIMITER=,
      - INPUT_FIELDS=legId,startingAirport,destinationAirport,totalFare,travelDuration,segmentsArrivalAirportCode
      - OUTPUT_FIELDS=legId,startingAirport,destinationAirport,travelDuration,segmentsArrivalAirportCode
      - INPUT=vuelos_tres_escalas_o_mas
      - OUTPUT=vuelos_dos_mas_rapidos
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=EXCHANGE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${FILTER_DOS_MAS_RAPIDOS_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  processor_dos_mas_rapidos:
    image: dos_mas_rapidos:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_dos_mas_rapidos
      - OUTPUT=vuelos_dos_mas_rapidos_sink
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=QUEUE
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  tagger_dos_mas_rapidos:
    deploy:
      replicas: ${TAGGER_DOS_MAS_RAPIDOS_REPLICAS}
    image: tagger:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_dos_mas_rapidos_sink
      - OUTPUT=vuelos_resultados
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${TAGGER_DOS_MAS_RAPIDOS_REPLICAS}
      - TAG_NAME=DOS_MAS_RAPIDOS
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
