version: "3.4"
name: tp1

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
    networks:
      - testing_net
    ports:
      - "5672:5672"
      - "15672:15672"

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py archivo.csv
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    depends_on:
      - server
    networks:
      - testing_net
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/archivo.csv:/archivo.csv
      - ./results:/results

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_resultados
      - OUTPUT=vuelos
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=QUEUE
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  filter_general:
    deploy:
      replicas: ${FILTER_GENERAL_REPLICAS}
    image: filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - DELIMITER=,
      - INPUT_FIELDS=legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,totalTravelDistance,segmentsDepartureTimeEpochSeconds,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
      - OUTPUT_FIELDS=legId,startingAirport,destinationAirport,totalFare,totalTravelDistance,travelDuration,segmentsArrivalAirportCode
      - INPUT=vuelos
      - OUTPUT=vuelos_filtered
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=EXCHANGE
      - REPLICAS_COUNT=${FILTER_GENERAL_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  filter_avg_max:
    deploy:
      replicas: ${FILTER_AVG_MAX_REPLICAS}
    image: filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - DELIMITER=,
      - INPUT_FIELDS=legId,startingAirport,destinationAirport,totalFare,totalTravelDistance,travelDuration,segmentsArrivalAirportCode
      - OUTPUT_FIELDS=startingAirport,destinationAirport,totalFare
      - INPUT=vuelos_filtered
      - OUTPUT=vuelos_avg_max
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=EXCHANGE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${FILTER_AVG_MAX_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  load_balancer:
    deploy:
      replicas: ${LOAD_BALANCER_REPLICAS}
    image: load_balancer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_avg_max
      - OUTPUT=vuelos_avg_max_balanced
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=EXCHANGE
      - REPLICAS_COUNT=${LOAD_BALANCER_REPLICAS}
      - GROUPER_REPLICAS_COUNT=${GROUPER_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  grouper_1:
    image: grouper:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=1
      - LOGGING_LEVEL=DEBUG
      - VUELOS_INPUT=vuelos_avg_max_balanced
      - VUELOS_OUTPUT=vuelos_max_avg_filtered
      - MEDIA_GENERAL_INPUT=media_general_sink
      - MEDIA_GENERAL_OUTPUT=media_general
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=EXCHANGE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${GROUPER_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  grouper_2:
    image: grouper:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=2
      - LOGGING_LEVEL=DEBUG
      - VUELOS_INPUT=vuelos_avg_max_balanced
      - VUELOS_OUTPUT=vuelos_max_avg_filtered
      - MEDIA_GENERAL_INPUT=media_general_sink
      - MEDIA_GENERAL_OUTPUT=media_general
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=EXCHANGE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${GROUPER_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  grouper_3:
    image: grouper:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REPLICA_ID=3
      - LOGGING_LEVEL=DEBUG
      - VUELOS_INPUT=vuelos_avg_max_balanced
      - VUELOS_OUTPUT=vuelos_max_avg_filtered
      - MEDIA_GENERAL_INPUT=media_general_sink
      - MEDIA_GENERAL_OUTPUT=media_general
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=EXCHANGE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${GROUPER_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  processor_media_general:
    image: media_general:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=media_general
      - OUTPUT=media_general_sink
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=EXCHANGE
      - GROUPER_REPLICAS_COUNT=${GROUPER_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  processor_max_avg:
    deploy:
      replicas: ${PROCESSOR_MAX_AVG_REPLICAS}
    image: max_avg:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_max_avg_filtered
      - OUTPUT=vuelos_max_avg_sink
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${PROCESSOR_MAX_AVG_REPLICAS}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

  tagger_max_avg:
    deploy:
      replicas: ${TAGGER_MAX_AVG_REPLICAS}
    image: tagger:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - INPUT=vuelos_max_avg_sink
      - OUTPUT=vuelos_resultados
      - RABBIT_HOST=rabbitmq
      - INPUT_TYPE=QUEUE
      - OUTPUT_TYPE=QUEUE
      - REPLICAS_COUNT=${TAGGER_MAX_AVG_REPLICAS}
      - TAG_NAME=MAX_AVG
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
